version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/project
hooks:
  BeforeInstall:
    - location: deploy_scripts/BeforeInstalling.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/AfterInstalling.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/ApplicationStartint.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy_scripts/ApplicationStopping.sh
      timeout: 300
      runas: root